### ISSUE TITLE
openLRSng OLED

### ISSUE THREAD

**Issue by eslanek** [openLRSng/openLRSng#101]
I would like to implement an OLED by the I2C port on the transmitter.
My question is, which part of the code can cause problems to add the LCD control code ?
I would like to create a similar funtion to the existing one in the sketch dialog.h  to manipulate parameters from the LCD and some switch. What you think is the best option, rewrite the code , or use a mini Arduino to communicate over the serial port whit dialog.h .

**Comment by kh4** [comment]
It may be hard to fit code for handling a OLED display (with fonts etc) into the available flash. Especially the type 6 flash is really tight,

**Comment by csurf** [comment]
@mikeller, another good candidate for closure...
