### ISSUE TITLE
LoRa Support planned?

### ISSUE THREAD

**Issue by fofi1** [openLRSng/openLRSng#103]
Hi,

it isn't really an issue , its more like a question/idea. 

Do you plan to support Lora Transceivers? At the moment there is only the TBS Crossfire that uses the LoRa Transceiver SX1272. Im totally impressed by the Range and Stability of this system, even under extreme circumstances it works without any glitches.

Greetings from Germany :)

**Comment by slimline33** [comment]
I like the idea, too! This would be a nice feature... :+1: it's not a issue its a feature!

**Comment by kh4** [comment]
Yeah I have looked a bit on them but there is no real plans.

I guess LoRa chips are a good candidate for our next gen stuff 'uberLRS',
