### ISSUE TITLE
Beacon is out of frequency

### ISSUE THREAD

**Issue by villamany** [openLRSng/openLRSng#105]
Im using the beacon function but real frequency is one channel down. I E: if i want beacon at PMR ch1 i need to selct PMR ch2 on the cli interface.

**Comment by kh4** [comment]
Which frequencies are you referring to, (EU) PMR or (US) FRS.

You can also enter beacon frequency manually.

**Comment by villamany** [comment]
thanks. I use PMR channels (EU). 
I already got it working by setting one channel plus than wanted.

**Comment by csurf** [comment]
@villamany
I tested this feature for multiple PMR channels (configured from command line), and it works as expected; no issues found...

FYI, I referenced the above PR to note that there's a fix in the queue for extending the channel range to 16 channels for PMR446 (Configurator will also need to be updated eventually).

@mikeller (@kh4 ?) 
Please close this issue out...
