### ISSUE TITLE
Channel 1 gone/not working

### ISSUE THREAD

**Issue by pyr8** [openLRSng/openLRSng#110]
I am having an issue with "Channel 1" not working on a "OrangeRx Open LRS 433MHz".

No matter what pin I assign channel 1 too, I cannot get the signal to work.

Using latest firmware (2016.02.28-3.8.8)

Any ideas?

**Comment by kh4** [comment]
Is there any output on the selected output pin?

Does the channel 1 appear in PPM stream as it should?

**Comment by csurf** [comment]
@pyr8 
Are you still having this issue? 
If not, please close this out.
If so, please provide more info...

**Comment by csurf** [comment]
no response, closing...
