### ISSUE TITLE
Broken binary firmware link

### ISSUE THREAD

**Issue by DavidDavidov** [openLRSng/openLRSng#111]
https://github.com/openLRSng/openLRSng says:

Binary firmware images are also available from
https://github.com/openLRSng/openlrsng.github.com/tree/master/binaries

but this link returns HTTP error 404 - missing page.

**Comment by ABLomas** [comment]
Temporary fix (thanks englishman): http://openlrsng.org/releases/v3.8.8/433/
(until it's fixed)
