### ISSUE TITLE
PX4/APM compatibility

### ISSUE THREAD

**Issue by alexFab** [openLRSng/openLRSng#113]
px4 doesn't recognize my openLRS RX (submicroLRS). But [this](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/generate-ppm-signal/Generate_PPM_signal_nodelay.ino) simple ppm simulator works fine with px4. 
ppm signal from openLRS looks pretty much the same like ppm from simulator but inverted. 

Any Ideas were the problem is?

**Comment by alexFab** [comment]
the signal from the ppm simulator looks like [this](http://openrcforums.com/forum/viewtopic.php?f=115&t=4277&p=63341&hilit=inverted#p63890) Signal.

**Comment by kh4** [comment]
Both polarities of PPM signal are widely used, I can implement a flag to allow swapping polarity.

However, in case you are not using telemetry you should consider switching to SUMD or SBUS.

**Comment by gregd72002** [comment]
I would be interested to see this too

**Comment by AlexFa** [comment]
> Both polarities of PPM signal are widely used, I can implement a flag to allow swapping polarity.

I would really like to have the possibility to swap the polarity by software. I found a hardware solution but that means more wiring..

**Comment by csurf** [comment]
@mikeller 
we should probably close this out, as the guys with the PX4 issue seem to have figured it out, unless there's still a desire to add new logic on RX side to invert the PPM signal?

**Comment by mikeller** [comment]
@csurf: Not sure about this one - inverted PPM does not seem to be that common. But adding the option to output inverted PPM would be trivial, so if it's solving somebody's problem then why not?

**Comment by csurf** [comment]
@mikeller 
done. let's close this out...

**Comment by mikeller** [comment]
@csurf: Yep. If you add `Fixes #<issue number>` to a pull request, the referenced issue will be closed by the system when the pull request is merged.
