### ISSUE TITLE
Custom firmware 

### ISSUE THREAD

**Issue by DeadBrain1** [openLRSng/openLRSng#115]
Hi can someone explain why any custom firmware doesnt work also when uploading openlrsng firmware from arduino it doesnt work so i must use Chrome configurator to upload firmware but i cant edit it 
From forums i can see that lot of people have  the same problem
We need tutorial for how to create custom firmware and upload i to arduino 
Please any help

**Comment by kh4** [comment]
Well... newer openLRSng stuff has optiboot bootloader on them so you need to use slightly different flashing protocol. See https://bigdanzblog.wordpress.com/2014/10/23/installing-the-optiboot-loader-on-an-arudino-nano-to-fix-the-watch-dog-timer-wdt-issue/ towards the end where it talks about boards.txt.

I do not compile with Arduino anymore but with make and avr-gcc directly, Arduino support will likely be dropped in some forthcoming release in favor of some saved flash and some better functionality.

**Comment by DeadBrain1** [comment]
Sorry the problem was that i was using newer version of arduino software 1.6.x.x but on older 1.0.x.x it works perfectly 
I will try to install optiboot on my arduino.

**Comment by csurf** [comment]
issue appears resolved, closing...
