### ISSUE TITLE
SBUS into 1W Rx as Tx

### ISSUE THREAD

**Issue by geekness** [openLRSng/openLRSng#132]
I have a custom ground station that has a 1W Rx used as a Tx. 
Does the current firmware allow the 1W Rx used as Tx to take an SBUS signal from the ground station to send to my aircraft? 
Does it require a hardware mod? 
Which pin should the sbus wire be connected to? 
Is it configured in the configurator?

**Comment by mikeller** [comment]
SBus goes into the serial port Rx pin (the same that's used to flash the firmware). And yes, setting serial speed to `SBUS` will enable it.

**Comment by geekness** [comment]
@mikeller thanks.
I assume that the pin labelled "PORT7/RX" is the serial in then?
Do I still power the 1W module with 5V into the BATT & GND port? Or does it need to be fed by the servo pins?

**Comment by mikeller** [comment]
Not knowing what hardware you are using, I would think so. Also, the way power is supplied should not change.

**Comment by csurf** [comment]
@geekness 
Please close this out if you've managed to get it sorted...
