### ISSUE TITLE
Remove 8MHz support?

### ISSUE THREAD

**Issue by csurf** [openLRSng/openLRSng#195]
I'm a bit confused by the 8MHz support in the code. Both the makefile and code have options for supporting an 8MHz XTAL. However, I don't even think that hardware with 8MHz oscillators exist "in the wild." 

In fact, it looks like only "RX type 8" is setup for the option of an 8MHz build. However, hardware.h even has a compiler warning setup for hardware type 8 if the CPU clock isn't set to 16MHz. This contradicts the idea of it being meant to also run 8MHz.

Can we simply clean up the makefile & code and remove the 8MHz support?

**Comment by geofrancis** [comment]
I think it was more of an experiment to run with the internal clock so it could be made with a 328 pu

**Comment by csurf** [comment]
ok, so then it should be safe to remove?

**Comment by geofrancis** [comment]
yes as far as i know no hardware ever came of it.

**Comment by csurf** [comment]
ok. thanks for the info.
removing & closing...
