### ISSUE TITLE
Cant setup serial bridge, any specific setup needed ?

### ISSUE THREAD

**Issue by tech0x** [openLRSng/openLRSng#206]
Hello,

I use master version of OpenRLSng on the tx and rx,
any specific options needed for setup transparent bridge ?

**Comment by csurf** [comment]
@tech0x 
there's probably a bug in the serial link code, as I also had issues getting it to work bi-directional with the current code base; It would work in one direction only, although ATM I can't remember if it was from RX to TX or TX to RX. 

I'll need to take a look at it, but it might be a while 'cuz I'm working on other stuff.

**Comment by tech0x** [comment]
What can I do for You, to help solve this issue ?

**Comment by csurf** [comment]
@tech0x 
- make sure you have 'TX' and 'RX' setup on outputs for RX module (do this via Configurator)
- make sure to setup the correct serial baudrate on the TX side (via Configurator)
- setup serial connection to both TX and RX simultaneously (using FTDI adapter on RX or something)
- use a terminal app to open serial connections to both TX and RX, using correct baudrate setting that you setup above
- test sending serial data on each terminal using keyboard
- you should see the characters appear on the other terminal (i.e., from TX to RX and from RX to TX)
- report back and let me know what you find...

If I remember correctly, it only worked in one direction...

**Comment by tech0x** [comment]
Ok thank You, I will test it.
I found missed TXD option in the Channel Output, is this ok ?

**Comment by csurf** [comment]
You need to select TXD and RXD in the channel outputs for the RX.

**Comment by csurf** [comment]
@tech0x 
what versions of configurator & firmware are you using?
This is a bug, but it should have been fixed.

**Comment by tech0x** [comment]
Both firmware and configurator downloaded from this url master version week or more time ago.
https://github.com/openLRSng/openLRSng

But I test version 3.8.8 and they works fine.
Ok I download current master and test them again.

**Comment by tech0x** [comment]
I make the test.
Today current master branch have this problem.

**Comment by csurf** [comment]
@tech0x 
ok, I'm working on it.
what type of TX and RX hardware are you using?

**Comment by csurf** [comment]
@tech0x 
there's a pending PR that should fix the Configurator issue, but it won't necessarily resolve the serial bridge issue. If & when the PR gets approved, you'll be able to re-pull master and test again. 

Unfortunately, I don't have time to fully test the serial bridge behavior right now. You'll have to wait until the PR is approved and merged so that you can try it out. Or, if you know how to pull a PR, you might want to try testing the PR directly. Then, we can proceed with testing&debugging the serial bridge issue...

**Comment by csurf** [comment]
@tech0x 
please try testing from master now...

**Comment by csurf** [comment]
@tech0x 
ok, so we've confirmed that TX->RX serial bridging works, but it's broken in the other direction. I'm pretty sure where in code the problem exists. I'll take a look at it in a while.

**Comment by csurf** [comment]
update with some test results:
- 3.8.8 TX with 3.9.0 RX, serial bridge works fine in both directions
- 3.9.0 TX with 3.8.8 RX, connection / link loss issues, can't get both to maintain link sync'ed. FYI, this relates to #205 

There's definitely an issue on the TX side. 
Will have to look into this further.

**Comment by csurf** [comment]
@tech0x 
I found & fixed the problem.
try downloading & testing from master again as soon as PR #210 gets merged...

**Comment by tech0x** [comment]
Thank You,

at first look all works,
but at start terminal session rx get few unknown symbols
 ��test
321

and tx 
OpenLRSng TX starting 3.9 on HW 5
�test
123

**Comment by tech0x** [comment]
Last RX version  works on Atmega 168, great works guys!
