### ISSUE TITLE
Problem with Mavlink data from ground control to Vehicle 

### ISSUE THREAD

**Issue by dhanyweb** [openLRSng/openLRSng#225]
Hi
In the past few days I tried setting up OpenLRS to work with Mavlink but only succeeded with one-way communication. sensors, GPS coordinates, voltage & current,rssi, all can be read well by the GCS, in this case I use QGroundControl and MissionPlanner, both can read data with but both of them can't send commands to the vehicle at all, arming / disarming commands, reading waypoints and sending waypoints doesn't work at all, I've tried changing the data rate, serial rate both in openLRS and in the flight controller but still can't make it work, any suggestion?am i doing wrong in setting / procedure?

**Comment by mikeller** [comment]
Hi @dhanyweb. Vanilla openLRSng does not support Mavlink. Maybe you want to try https://github.com/openLRSng/openLRSng/pull/80#issuecomment-341961536 to use a fork of openLRSng that does support Mavlink?

**Comment by dhanyweb** [comment]
I will give it a try,thank you mikeller
