### ISSUE TITLE
put actual release notes on RC3 release page ?

### ISSUE THREAD

**Issue by fiveangle** [openLRSng/openLRSng#232]
This I think covers most of it...

openLRSng 3.9.0-rc3

Fixes:
Fix start-up timing issue for 32u4
Fixed warning in RX.h
Fixed PPM signal monitor
Fix BOARD_TYPE label for TX startup message
Extend watchdog timer for lost-model beacon

Features:
Extend PMR446 channel range to 16 channels
Make TX module baud rate configurable
Added support for inverted PPM output on RX
Added support for binary proto on RX side
Added support for building with PlatformIO (Arduino no longer required, and will allow for building with alternate MCU targets)

openLRSng 3.9.0-rc2

Fixes:
changed build infrastructure to fix the problems with serial connections in 3.9.0-rc1;
updated version number to 3.9.0. (#136);
removed include for unneeded library (#137).
openLRSng 3.9.0-rc1

Features:
added support for MULTIPROTOCOL protocol on TX (#122);
normalised encoding of SBUS input / output against other protocols (#123);
improved efficiency of RX code (#127);
updated Makefile for arduino 1.8.4 (#134).

Thanks,

-=dave

**Comment by mikeller** [comment]
@fiveangle: Thanks, appreciated. I've updated the release information.
