### ISSUE TITLE
Improved beacon/buzzer idea

### ISSUE THREAD

**Issue by readerror67** [openLRSng/openLRSng#41]
Beacon ET Phone Home

Idea:
Utilizing the 'call' button on an inexpensive handheld radio (Baofeng UV-5R for example) to trigger remote beacon and/or buzzer.

Implementation (This is under the assumption of a new battery backup, small 1s 300mah, more on this later):
1) RX loses PPM signal, enters failsafe then beacon mode.
2) In between 'beacons' the RX will listen on a specific channel (435.00MHz)
3) If the 'noise' or RSSI crosses a certain threshold, the beacon is re-transmitted within a short period of time after the 'call'.
4) Audible beep is fired off (using buzzer circuitry) after this beacon based on duration of the 'call', this is used to hone in on the location once you are somewhat close as the model may be in a bush not visible.

Benefits:
1) It would be much faster to get a bearing as to where to head direction wise since one can manually fire off the beacon, spin in circles until they feel they have a better idea where the model is located.
2) The audible 'beep' can be set on a threshold as to not waste power, if the 'call' is longer than 2 seconds, the buzzer circuitry is activated.

**Comment by kh4** [comment]
I may give a shot at this today ;-)

**Comment by kh4** [comment]
Implemented by 4669e8a

**Comment by kh4** [comment]
Hmh the audible part needs to be done still...

**Comment by csurf** [comment]
@readerror67 
The 'ET'/interactive beacon was setup a long while back.
Can you go ahead and close this out?
