### ISSUE TITLE
Flashing RX code onto custom RFM23BP Hardware

### ISSUE THREAD

**Issue by Timvrakas** [openLRSng/openLRSng#69]
Hello, I'm trying to load RX code onto a receiver I designed. The receiver is very similar to the OpenLRSminiRX, but uses a 1W RFM23BP-443-S2. I tried loading RX code board type 5, and I get the following message from the RX:

"OpenLRSng RX starting 3.6.4 on HW 5
EEPROM data not valid or bind jumpper set, forcing bind
Waiting bind

Got pkt"

nothing from the transmitter side seems to make much of a difference...

You can look at board designs if you want, they are under my account in repo "openLRS-APM"

EDIT: Also worth noting that the RFM23BP gets really hot.

**Comment by haroldmars** [comment]
Me too ran into this case yesterday, you are not alone :(
IMPORTANT: when using TX as RX, remember to remove the SDN from PB1, and connect it to GND!
