### ISSUE TITLE
1W transmitter as receiver

### ISSUE THREAD

**Issue by dispetto77** [openLRSng/openLRSng#84]
Hi, according with issue #74, i would like to contribute with this project.
Do you think is it possible to use ppm input as ppm output? like ultimatelrs, i would like to have a pinout with
-GND
-VCC
-Serial PPM
-Telemetry TX
- Telemetry RX
- Analog RSSI (directly from chip pinout)

I tried the last code but ppm from buzzer isn't the best and telemetry tx-rx isn't working
Thank you

**Comment by kh4** [comment]
Works for me, closing this off.
