### ISSUE TITLE
Compile for Broversity fails

### ISSUE THREAD

**Issue by JohnieBraaf** [openLRSng/openLRSng#86]
Hi trying to compile with the Arduino IDE I got the following message:

/serialPPM.h: In function 'void sendSBUSFrame(uint8_t, uint8_t)':
serialPPM.h:75: error: call of overloaded 'write(int)' is ambiguous
note: candidates are: virtual size_t HardwareSerial::write(uint8_t)
note:                 size_t Print::write(const char*)

I have resolved it with a type cast: 

Serial.write(<b>(uint8_t)</b>SBUS_TAIL);

**Comment by kh4** [comment]
I will add the cast.  Notably compilation with arduino is not verified anymore as project is built with make. 

Arduino support is deprecated and will be removed with 4.0 version (all arduino arduino references removed so that build obly needs avr-gcc.

**Comment by kh4** [comment]
Fixed in 42600a2
