### ISSUE TITLE
Documentation folder for .md files

### ISSUE THREAD

**Issue by JohnieBraaf** [openLRSng/openLRSng#89]
It would be great if there was a place were people can update documentation and configuration info.
I'm unable to update the wiki, so I guess adding a doc folder would enable people to share knowledge all in one place.

**Comment by kh4** [comment]
I can give wiki edit rights no problem ;) That is why I moved to wiki to separate repository. https://github.com/openLRSng/openLRSngWiki

**Comment by JohnieBraaf** [comment]
Yes, that would be great.
