### ISSUE TITLE
How to find older frimeware's for DTF UHF Hawkeye TX (can't bind with new Hawkeye 9ch RX)

### ISSUE THREAD

**Issue by Jar4yk** [openLRSng/openLRSng#93]
Hi, i want to attach frimeware to my old DTF UHF Hawkeye TX, with new Hawkeye 9ch RX, but they won't bind.

How to find all older than 3.8.3 versions exact for DTF UHF frimewares ?

**Comment by kh4** [comment]
http://openlrsng.org/releases/
