### ISSUE TITLE
FrSky emulation bug

### ISSUE THREAD

**Issue by NopeDK** [openLRSng/openLRSng#96]
Hello

I tried using the openLRSng on two OrangeRx receivers with my 9XR Pro, but for some reason the telemetry link is always "TmOK" even though I turn of the receiver.

I discussed the issue with MikeB of OpenRC (ersky9xr) and the result was that it was the emulation that is bugged.
http://openrcforums.com/forum/viewtopic.php?f=123&t=7024&sid=771b0f457f0436441cafb33a9188cfc2

Can this be fixed?

Thanks.

**Comment by kh4** [comment]
Yes, openLRSng sends telemetry frames regardless of connection being up, I can fix this quite easily.
