### ISSUE TITLE
Taranis TX low power causing cleanflight receiver bar fluctuations

### ISSUE THREAD

**Issue by Ninjarev** [openLRSng/openLRSng#97]
Dont know if anyone is having this problem..  When taranis transmitter drops to 7.8V using a LRS deluxe UHF transmitter module cleanflight has fluctuations in the channel bars in reciever tab. It gets worse as voltage drop gets lower. When it drops to 7.2V the UHF will not bind.  If I charge the radio back up to 8.4 volts it works fine..  Also note using a Sparky and the reviever is a mini DTF..

**Comment by kh4** [comment]
Please check by having the TX module connected to PC while taranis is low power, open up the signal monitor tab an see if the bars are stable there.

**Comment by Ninjarev** [comment]
Thanks for response I will check it next time battery is low 

 

JIM


----- Original Message -----

**Comment by csurf** [comment]
@Ninjarev,
did you ever get this tested and resolved? if so, please post back and close this issue out.

**Comment by csurf** [comment]
no response, closing...
